// <auto-generated />
using System;
using Ecommerce.Customers.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ecommerce.Customers.Infrastructure.Migrations
{
    [DbContext(typeof(ClienteDbContext))]
    [Migration("20250515134933_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Ecommerce.Customers.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CpfCnpj")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EnderecoBairro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EnderecoCep")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EnderecoCidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EnderecoComplemento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EnderecoEstado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EnderecoNumero")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EnderecoRua")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Clientes", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
